runner:
  phpcs:
    cmd: ./vendor/bin/phpcs --standard=./phpcs.xml --report=emacs ./src/PhpSample.php
    errorformat:
      - "%f:%l:%c: %trror - %m"
      - "%f:%l:%c: %tarning - %m"
    level: warning
