name: "PHP analysis on PR"

on:
  pull_request:

jobs:
  PHP_CodeSniffer_with_reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Composer Install
        run: composer install
      - name: Reviewdog Install
        run: curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b ./bin
      - name: Run PHPCS
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bin/reviewdog -conf=./.reviewdog.yml -reporter=github-pr-check
