name: "textlint"

on:
  push:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run npm install
        run: npm install
      - run: echo "::add-matcher::.github/problem-matcher.json"
      - name: Run textlint
        run: npm run textlint || true
